version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-commander:
    # localhost:8081
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis

# to start containers
# docker-compose -f redis-compose.yml up

# to remove the volumes
# docker-compose -f redis-compose.yml down -v