version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

# to start containers
# docker-compose -f redis-compose.yml up

# to remove the volumes
# docker-compose -f redis-compose.yml down -v