version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-commander:
    # http://localhost:8081
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis

  hazelcast:
    hostname: hazelcast1
    container_name: hazelcast1
    image: 'hazelcast/hazelcast'
    environment:
      - HAZELCAST_CONFIG=hz.yml
    volumes:
      - ./hazelcast.yml:/opt/hazelcast/hz.yml
    ports:
      - '5701:5701'
  management-center:
    # http://localhost:8082
    image: hazelcast/management-center
    hostname: management-center
    container_name: management-center
    ports:
      - "8082:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast1
      - MC_ALLOW_MULTIPLE_LOGIN=true
      - MC_ADMIN_USER=admin
      - MC_ADMIN_PASSWORD=hazelcast12

  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432