version: '3.9'
services:
  hazelcast:
    image: 'hazelcast/hazelcast'
    ports:
      - '5701:5701'

# to start containers
# docker-compose  -f hazelcast-compose.yml up

# to remove the volumes
# docker-compose -f hazelcast-compose.yml down -v

